name: Build and attach to release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and upload release
      uses: rust-build/rust-build.action@v1.4.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        MINIFY: "true"
        EXTRA_FILES: "README.md LICENSE.txt"
